name: AthletiX
description: AthletiX - Votre compagnon pour une vie plus saine et active

android: app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
ios: Runner/Assets.xcassets/AppIcon.appiconset/ic_launcher.png

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  flutter_svg: ^2.0.9
  http: ^1.1.0
  firebase_auth: ^4.16.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  flutter_secure_storage: ^9.0.0
  flutter_native_splash: ^2.3.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - .env
  - assets/AthletiX.svg
  - assets/LikeIcon.svg
  - assets/DoubleHaltereIcon.svg
  - assets/CommentIcon.svg
  - assets/AddPlus.svg
  - assets/MagGlass.svg
  - assets/Filter.svg
  - assets/Benchpress.png
  - assets/LetsGo.svg
  - assets/doigby.mp4
  - assets/Logo.png

# Gen Splash Screen "flutter pub run flutter_native_splash:create"
flutter_native_splash:
  color: "#FFFFFF"           # Couleur de fond du splash screen
  image: assets/Logo.png     # Chemin de l'image du splash screen
  android: true              # Activer pour Android
  ios: true                  # Activer pour iOS
