// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmXlgifhnaCaFVZnAX3x29FUKg1VVhDk',
    appId: '1:513800481598:web:c2298e5b4d3a0e71cc5a6f',
    messagingSenderId: '513800481598',
    projectId: 'ath-app-1ce7a',
    authDomain: 'ath-app-1ce7a.firebaseapp.com',
    storageBucket: 'ath-app-1ce7a.appspot.com',
    measurementId: 'G-76VMLTRCWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQTS7ZnImnMG9E4D60Rf048kwcLO2bP_I',
    appId: '1:513800481598:android:dc90f6a5b3d53151cc5a6f',
    messagingSenderId: '513800481598',
    projectId: 'ath-app-1ce7a',
    storageBucket: 'ath-app-1ce7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_sIqFY0ZNpvKW-JXo3OJdvVpDOzEv0Yw',
    appId: '1:513800481598:ios:b2915a951280c9f4cc5a6f',
    messagingSenderId: '513800481598',
    projectId: 'ath-app-1ce7a',
    storageBucket: 'ath-app-1ce7a.appspot.com',
    iosBundleId: 'fr.uca.iutclinf.athletix.sources',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_sIqFY0ZNpvKW-JXo3OJdvVpDOzEv0Yw',
    appId: '1:513800481598:ios:9af833f439bc0cd3cc5a6f',
    messagingSenderId: '513800481598',
    projectId: 'ath-app-1ce7a',
    storageBucket: 'ath-app-1ce7a.appspot.com',
    iosBundleId: 'fr.uca.iutclinf.athletix.sources.RunnerTests',
  );
}
